[package]
name = "randomize_words"
version = "0.1.0"
authors = ["Arturo J <arturo.jimenez@mytaxi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
